spring:
  datasource:
    url: jdbc:mysql://capmathdb.ch0e6swk0aar.ap-northeast-2.rds.amazonaws.com:3306/capmath
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
openai:
  model: gpt-4o
  secret-key: ${API_KEY}


server:
  port: 8080
  address: 0.0.0.0

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method

swagger:
  tag:
    auth: '01. 로그인/회원가입'
    math-quiz: '02. 수학문제'
    test: 'A. Test API'
logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: capmath
      path:
        quiz: quiz
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}